import type { Finding } from "./types";
import type { ExperienceScore } from "./experience-score";
import { pathsShareArea } from "./findings";

/**
 * PR Experience Diff — 変更されたコードに対応する画面へ小さい群れを集中投下し、
 * 「この PR でユーザー体験がどう変わったか」を PR コメントとして返すための部品群。
 * エントリポイントは diff.ts（`shoal diff`）。
 */

// ================================================================
// Route inference — 変更ファイルから影響ルートを推定する
// ================================================================

const PAGE_EXT = /\.(tsx|jsx|ts|js|vue|svelte)$/;

function normalizeRoute(route: string): string {
  const r = `/${route.replace(/^\/+|\/+$/g, "")}`;
  return r === "//" ? "/" : r;
}

/** フレームワーク規約（Next.js pages / app router 等）で変更ファイルをルートにマッピングする */
export function inferRoutesFromFiles(changedFiles: string[]): string[] {
  const routes = new Set<string>();

  for (const file of changedFiles) {
    const f = file.replace(/\\/g, "/");

    // Next.js pages router: (src/)pages/foo/bar.tsx → /foo/bar, pages/index.tsx → /
    const pages = f.match(/(?:^|\/)pages\/(.+)$/);
    if (pages && PAGE_EXT.test(pages[1])) {
      const p = pages[1].replace(PAGE_EXT, "");
      if (p.startsWith("api/") || p.startsWith("_")) continue; // API routes / _app / _document
      routes.add(normalizeRoute(p.replace(/\/?index$/, "")));
      continue;
    }

    // Next.js app router: (src/)app/foo/page.tsx → /foo（layout も同じルート扱い）
    const appDir = f.match(/(?:^|\/)app\/(.*?)(page|layout)\.(tsx|jsx|ts|js)$/);
    if (appDir) {
      const dir = appDir[1].replace(/\/$/, "");
      // route groups "(group)" はパスに現れない
      const cleaned = dir.split("/").filter((seg) => seg && !/^\(.*\)$/.test(seg)).join("/");
      routes.add(normalizeRoute(cleaned));
      continue;
    }

    // 汎用: views/ or routes/ ディレクトリ
    const generic = f.match(/(?:^|\/)(?:views|routes)\/(.+)$/);
    if (generic && PAGE_EXT.test(generic[1])) {
      routes.add(normalizeRoute(generic[1].replace(PAGE_EXT, "").replace(/\/?index$/, "")));
      continue;
    }
  }

  return [...routes].sort();
}

/** git 推定ルートと page-hash キャッシュ上の関連パスをマージする */
export function expandFocusRoutesWithPageCache(routes: string[], cachedPaths: string[]): string[] {
  if (routes.length === 0) return routes;
  const merged = new Set(routes);
  for (const route of routes) {
    for (const cached of cachedPaths) {
      if (pathsShareArea(route, cached)) merged.add(cached);
    }
  }
  return [...merged].sort();
}

// ================================================================
// PR number — CI 環境から対象 PR を特定する
// ================================================================

/** SHOAL_PR_NUMBER 明示指定 > GitHub Actions の GITHUB_REF (refs/pull/123/merge) */
export function resolvePrNumber(env: NodeJS.ProcessEnv = process.env): number | null {
  const explicit = parseInt(env.SHOAL_PR_NUMBER ?? "", 10);
  if (Number.isFinite(explicit) && explicit > 0) return explicit;
  const m = (env.GITHUB_REF ?? "").match(/^refs\/pull\/(\d+)\//);
  if (m) return parseInt(m[1], 10);
  return null;
}

// ================================================================
// Summary — PR コメント用 markdown
// ================================================================

export interface DiffSummaryInput {
  runId: string;
  baseRef: string;
  focusRoutes: string[];
  findings: Finding[];
  experience: ExperienceScore | null;
}

const CATEGORY_EMOJI: Record<string, string> = {
  bug: "🐛",
  ux: "🎨",
  "feature-request": "💡",
  "goal-gap": "🎯",
};

export function formatDiffSummary(input: DiffSummaryInput): string {
  const { runId, baseRef, focusRoutes, findings, experience } = input;

  const lines: string[] = ["## 🐟 shoal — Experience Diff", ""];

  if (experience) {
    const { latest, delta } = experience;
    const deltaStr = delta == null ? "" : delta > 0 ? ` (▲${delta} vs previous run)` : delta < 0 ? ` (▼${Math.abs(delta)} vs previous run)` : " (±0 vs previous run)";
    lines.push(`**Experience Score: ${latest.score}/100**${deltaStr}`, "");
  }

  lines.push(
    focusRoutes.length > 0
      ? `Agents focused on the areas this PR touches (diff vs \`${baseRef}\`): ${focusRoutes.map((r) => `\`${r}\``).join(", ")}`
      : `No route mapping could be inferred from the diff vs \`${baseRef}\` — agents explored freely.`,
    "",
  );

  if (findings.length === 0) {
    lines.push("Agents completed their sessions without reporting any findings. ✅");
  } else {
    lines.push(`### Findings (${findings.length})`, "");
    for (const f of findings.slice(0, 10)) {
      const emoji = CATEGORY_EMOJI[f.category] ?? "📝";
      const excerpt = f.body.length > 240 ? `${f.body.slice(0, 240)}…` : f.body;
      lines.push(`- ${emoji} **[${f.category}] ${f.title}** — ${f.agentName}`, `  ${excerpt.replace(/\n/g, " ")}`);
    }
    if (findings.length > 10) lines.push(`- …and ${findings.length - 10} more (see the run report)`);
  }

  lines.push("", `<sub>run \`${runId}\` — AI agents experienced this app as real users. Generated by [shoal](https://github.com/m8i-51/shoal).</sub>`);
  return lines.join("\n");
}

// ================================================================
// PR comment
// ================================================================

export async function postPrComment(
  body: string,
  opts: { token: string; repo: string; prNumber: number },
): Promise<boolean> {
  const [owner, repo] = opts.repo.split("/");
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/issues/${opts.prNumber}/comments`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${opts.token}`,
      "Content-Type": "application/json",
      Accept: "application/vnd.github+json",
    },
    body: JSON.stringify({ body }),
  });
  if (!res.ok) {
    const msg = await res.text().catch(() => "");
    console.error(`[diff] failed to comment on PR #${opts.prNumber} (${res.status}): ${msg.slice(0, 200)}`);
  }
  return res.ok;
}
